using System.Windows.Controls;

namespace FalcaPOS.AddInventory.Views
{
    /// <summary>
    /// Interaction logic for ViewStock.xaml
    /// </summary>
    public partial class ViewStock : UserControl
    {

        public ViewStock()
        {
            InitializeComponent();

        }

        //private void DataGrid_AutoGeneratedColumns(object sender, EventArgs e)
        //{
        //    var grid = (DataGrid)sender;
        //    foreach (var item in grid.Columns)
        //    {
        //        if (item.Header.ToString() == "Barcode")
        //        {
        //            item.DisplayIndex = grid.Columns.Count - 1;
        //            break;
        //        }
        //    }
        //}
    }
}
